package OOP3.Overriding;

public class main {

//    WHEN THE CHILD CLASS HAS THE SAME METHOD AS THE PARENT CLASS BUT THE BUT
//    THE BODY OF THE FUNCTION IS DIFFERENT THAT IS IN THE CASE OF THE SHAPES EXAMPLE
}
